CREATE DATABASE IF NOT EXISTS green_plant_shop CHARACTER SET utf8mb4;
USE green_plant_shop;

CREATE TABLE plant(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price INT NOT NULL,
    image VARCHAR(255) NOT NULL,
    place VARCHAR(255) NOT NULL
) DEFAULT CHARACTER SET=utf8;


CREATE TABLE goods(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price INT NOT NULL,
    image VARCHAR(255) NOT NULL,
    difficulty INT NOT NULL
) DEFAULT CHARACTER SET=utf8;